### ISSUE TITLE
Update Add-on help link on addons.mozilla.org

### ISSUE THREAD

**Issue by deadcombo** [Rayquaza01/quick-tab-switch#20]
The help link on https://addons.mozilla.org/en-US/firefox/ points to https://github.com/Rayquaza01/quick-tab-switch/blob/master/extension/help/help.md instead of the new PDF link.

Cheers.

**Comment by Rayquaza01** [comment]
The help link on AMO now links to https://github.com/Rayquaza01/quick-tab-switch/blob/master/src/help.pdf
Thanks!
