### ISSUE TITLE
Setting to sort results

### ISSUE THREAD

**Issue by deadcombo** [Rayquaza01/quick-tab-switch#21]
Hi,

I prefer to view my tabs in order of last visited, it often helps me switch tabs.
It'd be an appreciated addition.

Cheers.

**Comment by Rayquaza01** [comment]
This is included in the new version, 1.2.0. There is a new option, called "Sort Tabs". The default is tab order (tabs are shown in the order they appear in the tab bar). You can also set it to last accessed (tabs are shown in the order they were last accessed, with the currently selected tab at the top of the list).
