### ISSUE TITLE
Using Firefox View Makes It Appear In Tab List

### ISSUE THREAD

**Issue by Rayquaza01** [Rayquaza01/quick-tab-switch#25]
When you open QTS, it shows just the open tabs from the browser's tab bar. However, if you select the Firefox View icon at any point, from that point on Firefox View will appear as a tab in the QTS tab list, right after the first tab in the tab bar. This is probably not expected/wanted behavior.

Maybe we can just skip over it in QTS? We could definitely skip over the URL, which is `about:firefoxview-next`, but that might not be what's wanted if a user intentionally opens Firefox View in a tab for whatever reason.

**Comment by deadcombo** [comment]
I would say the latter, it being accessible only through an icon seems like mozilla didn't intend for it to be accessed directly. Might as well keep it consistent.
Users interested in the former behavior can set a bookmark shortcut to it or something like it.

**Comment by Rayquaza01** [comment]
I've added a basic option to filter Firefox View from the list. It's enabled by default and simply skips `about:firefoxview-next`. I think this should probably be enough.

**Comment by Rayquaza01** [comment]
Firefox View's URL has changed to `about:firefoxview`, so the filtering code needs to be updated.

Also, it seems Firefox View can't be disabled from `about:config` anymore.
